languageCode: "en-us"
baseUrl: ""
title: "DHM"
theme: "anubis"
paginate: 10
disqusShortname: yourdiscussshortname
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: ""
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "assets" directory (don't use main.css filename)
  customJS:
    - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark 
  readMore: false
  webmentions:
    login: hugo-theme-anubis
    pingback: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
